### ISSUE TITLE
Heap crash while executing demo application "netlicensing_client_demo.cc"

### ISSUE THREAD

**Issue by KrishnanRK** [Labs64/NetLicensingClient-cpp#2]
I have download "NetLicensingClient-cpp-master" and built it with curl in windows 10 visual studio 12 2013. While trying to execute "netlicensing_client_demo.cc ", I am getting heap crash. I have followed the build steps carefully and didn't get any errors or warnings while building. Can somebody help with this issue?

Steps to reproduce:
LibCurl:
--------
    1) Download the curl-7.56.1 of curl source package.
      https://github.com/curl/curl/releases
    2) Open "VS2013 x64 Native Tools Command Prompt" in Windows 10
    3) change directory to "winbuild"
    4) Build static lib using nmake command,
       nmake /f Makefile.vc mode=static VC=12 MACHINE=x64 ENABLE_WINSSL=yes

NetLicensing-CPP:
--------------------
    1) Download git repo from the following link,
      https://github.com/Labs64/NetLicensingClient-cpp
    2) Create build directory
    3) cmake .. -G "Visual Studio 12 Win64" -DCURL_INCLUDE_DIR=<include-curl-header-path> -DCURL_LIBRARY=<link-curl-lib-path>
    4) Open and build the solution file in Visual Studio.

Successful build log:
---------------------
D:\Projects\NetLicensing\NetLicensingClient-cpp-master\build>cmake -G "Visual Studio 12 Win64" -DCURL_INCLUDE_DIR="d:\Projects\NetLicensing\curl-7.56.1\curl-7.56.1\builds\libcurl-vc12-x64-release-static-ipv6-sspi-winssl\include" -DCURL_LIBRARY="d:\Projects\NetLicensing\curl-7.56.1\curl-7.56.1\builds\libcurl-vc12-x64-release-static-ipv6-sspi-winssl\lib\libcurl_a.lib" ..
-- The C compiler identification is MSVC 18.0.40629.0
-- The CXX compiler identification is MSVC 18.0.40629.0
-- Check for working C compiler using: Visual Studio 12 2013 Win64
-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CURL: d:/Projects/NetLicensing/curl-7.56.1/curl-7.56.1/builds/libcurl-vc12-x64-release-static-ipv6-sspi-winssl/lib/libcurl_a.lib (found version "7.56.1")
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Projects/NetLicensing/NetLicensingClient-cpp-master/build

**Comment by yushkevich** [comment]
Please, provide more info about your Heap crash while executing demo application.

Anyway, You use static mode for build curl library. At this moment we support only dll mode. And another thing: you use -**DCURL_INCLUDE_DIR**=<include-curl-header-path> -**DCURL_LIBRARY**=<link-curl-lib-path> parameters instead you should use **CMAKE_PREFIX_PATH**.

**Comment by renaud-sc** [comment]
I am getting a crash too. It may or may not be the same issue. The crash happens in netlicensing.cc line 185 while trying to parse the answer received from the server.

The answer from the server looks like this:
{"Signature":null,"infos":{"info":[{"value":"Requested licensee does not exist and the productNumber is not provided","id":"NotFoundException","type":"ERROR"}]},"items":null,"id":null,"ttl":null}
Which I guess  justify why a crash when trying to parse "null" as a date ;-)

As I am fully new to netLiceensing, it's bit hard for me to know why these values are "null". Could anyone help ?

It would probably be a good idea to make the demo code a little bit more solid anyway.

**Comment by yushkevich** [comment]
The crash was fixed. 
Demo code was improved.
